export const typography = {
  ADD_SERVICE: "Добавить услугу",
  ADD_DOCTOR: "Добавить врача",
  SEVICE_LINK: "services/create",
  SUBSEVICE_LINK: "/subservices/create",
  SUBDIRSEVICE_LINK: "/subservice-direction/create",
  DOCTOR_LINK: "doctors/create",
  SERVICE_IMAGE: "./assets/dental_care.svg",
  SUBSERVICE_IMAGE: "../assets/subservice.svg",
  SUBDIRSERVICE_IMAGE: "../assets/subservice.svg",
  DOCTOR_IMAGE: "./assets/dentist.svg",
  ADD_SUBSERVICE: "Добавить подуслугу",
  ADD_SUBDIRSERVICE: "+ Направление подуслуги",
  ADD_ACTION: "Объявить акцию",
  ACTION_LINK: "/actions/create",
  ACTION_IMAGE: "/assets/action.svg",
  SPECIALIZATION_1: "Процедура Зубы за день",
  SPECIALIZATION_2: "Процедура All-on-4",
  SPECIALIZATION_3: "Зубные импланты",
  SPECIALIZATION_4: "Преображение улыбки",

  ADD_CONTENT_STYLE: {
    position: "fixed",
    bottom: "20px",
    left: "20px",
    zIndex: "999",
    cursor: "pointer",
    borderRadius: "10px",
    border: "none",
    textDecoration: "none",
    padding: "0.5%",
    backgroundColor: "rgba(218, 239, 241, 0.5)",
  },
  A: {
    textDecoration: "none",
    fontSize: "20px",
    padding: "5px",
  },
  IMAGE_DEFAULT_URL: "./assets/logo_mirastom.svg",
  EYE_IMAGE_URL: "./assets/eye.svg",

  TEXT_INFORM_CARD: [
    "Получите первоклассное стоматологическое лечение с использованием страхового покрытия! Работаем практически со всеми страховыми компаниями страны.",
    "Мы гордимся нашими сертификатами, которые подтверждают нашу компетентность и профессионализм. Мы постоянно совершенствуемся и следим за новыми технологиями и методиками в стоматологии, чтобы предоставить нашим пациентам лучшее качество лечения.",
    "Мы оказываем своим клиетам очень качественное лечение и уверены в его результате. Поэтому мы предлагаем нашим пациентам гарантию на наши стоматологические услуги. Мы также предоставляем возможности расчёта с помощью карт рассрочки многих беларусских банков",
  ],
  TITLE_INFORM_CARD: [
    "Лечение зубов по страховке",
    "Наши сертификаты",
    "Нам можно доверять",
  ],
};
