export const typography = {
  ADD_SERVICE: "Добавить услугу",
  ADD_DOCTOR: "Добавить врача",
  SEVICE_LINK: "services/create",
  SUBSEVICE_LINK: "/subservices/create",
  DOCTOR_LINK: "doctors/create",
  SERVICE_IMAGE: "./assets/dental_care.svg",
  SUBSERVICE_IMAGE: "../assets/subservice.svg",
  DOCTOR_IMAGE: "./assets/dentist.svg",
  ADD_SUBSERVICE: "Добавить подуслугу",
  ADD_ACTION: 'Объявить акцию',
  ACTION_LINK: '/actions/create',
  ACTION_IMAGE: '/assets/action.svg',

  ADD_CONTENT_STYLE: {
    position: "fixed",
    bottom: "20px",
    left: "20px",
    zIndex: "999",
    cursor: "pointer",
    borderRadius: "10px",
    border: "none",
    textDecoration: "none",
    padding: "0.5%",
    backgroundColor: "rgba(218, 239, 241, 0.5)",
  },
  A: {
    textDecoration: "none",
    fontSize: "20px",
    padding: "5px",
  },
};